name: CI/CD Pipeline (Local Development)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  local-development-placeholder:
    runs-on: ubuntu-latest

    steps:
      - name: Placeholder for Local Development
        run: echo "No deployment or tests. Project is being run locally only."
